Draft of learning objectives - Function development
rostools/r-pkg-intro pull request #25
Opened 2024-05-01 07:39 UTC by AndersAskeland

2024-05-01 08:04 UTC, AndersAskeland commented
Just realised that we might need to include something in relation to non standard evaluation / tidy evaluation. What does everyone think? I don't believe NSE is ever taught in any of the other courses.

2024-05-01 12:41 UTC, lwjohnst86 commented
@AndersAskeland I think we should definitely teach that because they will encounter it if they do any package dev

2024-05-01 12:52 UTC, lwjohnst86 requested changes
Great start! Here's some suggested changes 😁

2024-05-01 12:52 UTC, lwjohnst86 commented on sessions/function-development.qmd
> +-   Convert your R code into a function
```suggestion
-   Review and apply the workflow for converting code into a function.
```

2024-05-01 12:52 UTC, lwjohnst86 commented on sessions/function-development.qmd
> +
```suggestion

- Explain some software development and functional programming principles that underlie effective R package development
```

2024-05-01 12:52 UTC, lwjohnst86 commented on sessions/function-development.qmd
> +-   Make your function modular and reusable
```suggestion
-   Identify approaches and "code patterns" for writing your functions that ensure they are internally self-contained and reusable
```

2024-05-01 12:52 UTC, lwjohnst86 commented on sessions/function-development.qmd
> +    packages in your own package
```suggestion
-   Explain what dependency means in the context of packages and how you formally manage dependencies when writing functions as part of a package
```

I'm not sure if maybe package dependency makes more sense in another session or here, but we'll keep it here for now.

2024-05-28 19:38 UTC, AndersAskeland reviewed
Accepted changes

2024-05-28 19:42 UTC, AndersAskeland reviewed
Test

2024-05-28 19:49 UTC, AndersAskeland reviewed
@lwjohnst86 Should be ready for merging.

2024-08-07 12:11 UTC, lwjohnst86 approved these changes
Nice! I made some small edits and will merge now 😁

2024-08-07 12:11 UTC, merged